version: '3.9'

name: sab-cdn

networks:
  localnet: {}

volumes:
  sab-cdn-registry-data: {}

services:
  registry:
    build:
      context: docker/registry
    pull_policy: build
    image: sab-cdn-registry:latest
    container_name: sab-cdn-registry
    init: true
    networks:
      - localnet
    volumes:
      - sab-cdn-registry-data:/verdaccio/storage
    healthcheck:
      test:
        [
          'CMD',
          'wget --no-verbose --tries=1 --spider http://localhost:4873'
        ]
      start_period: 3s
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    environment:
      - UPLINK_REGISTRY_URL=https://registry.npmjs.org
      # Do not forget to align the config file as well: docker/registry/config.yaml
      # Either set an (bearer) auth token
      - UPLINK_AUTH_TOKEN
      # Or use username and password (basic) auth
      # - UPLINK_AUTH_USERNAME=username
      # - UPLINK_AUTH_PASSWORD=password

  server:
    depends_on:
      - registry
    build:
      context: .
      dockerfile: docker/cdn/Dockerfile
      args:
        - PORT=8080
    pull_policy: build
    image: sab-cdn-server:latest
    container_name: sab-cdn-server
    init: true
    networks:
      - localnet
    restart: unless-stopped
    environment:
      # Limit the allowed package scopes.
      # To allow only the @my-scope scope, set this to @my-scope.
      # To allow multiple scopes, provide space separated values: `@my-scope @my-other-scope`.
      # Omit the environment variable to allow all scopes.
      # - SCOPES=@my-scope
      # MAKE SURE TO OMIT THE TRAILING SLASH!
      - NPM_REGISTRY_URL=http://registry:4873
      # The internal cache can be configured with this variables:
      # - LRU_CACHE_MAX=40 # amount of overall cache items
      # - LRU_CACHE_MAX_SIZE=262144000 # max size of the cache in bytes
      # - LRU_CACHE_TTL=300000 # time to live for each cache item in ms
    ports:
      - 9000:8080
