version: '3.9'

name: sab-cdn

networks:
  localnet: {}

volumes:
  sab-registry-data: {}

services:
  registry:
    build:
      context: sab-registry.Dockerfile
    pull_policy: build
    image: sab-registry:latest
    container_name: sab-registry
    networks:
      - localnet
    volumes:
      - sab-registry-data:/verdaccio/storage
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4873 || exit 1
      start_period: 3s
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    env_file: .env.docker

  server:
    build:
      context: sab-server.Dockerfile
      args:
        - PORT=8080
    pull_policy: build
    image: sab-cdn:latest
    container_name: sab-cdn
    init: true
    restart: unless-stopped
    environment:
      # Limit the allowed package scopes.
      # To allow only the @my-scope scope, set this to @my-scope.
      # To allow multiple scopes, provide space separated values: `@my-scope @my-other-scope`.
      # Omit the value to allow all scopes.
      # - SCOPES=@my-scope
      - ORIGIN=http://localhost
      - NPM_REGISTRY_URL=https://registry.npmjs.org
      # Either set an (bearer) auth token
      - NPM_AUTH_TOKEN
      # Or use username and password (basic) auth
      # - NPM_AUTH_USERNAME
      # - NPM_AUTH_PASSWORD
    ports:
      - 9000:8080
