version: "3.8"

networks:
  localnet: {}

volumes:
  sab-cache-data: {}

services:
  data:
    image: redis
    container_name: "sab-cache"
    networks:
      - localnet
    volumes:
      - sab-cache-data:/data

  server:
    build: .
    image: sab/cdn:latest
    container_name: "sab-cdn"
    restart: always
    env_file: .env.docker
    environment:
      - CACHE_URL=redis://data:6379
      - DATA_URL=redis://data:6379
    depends_on:
      - data
    networks:
      - localnet
    ports:
      - "9000:8080"
