version: '3.9'

name: sab-cdn

networks:
  localnet: {}

volumes:
  sab-cdn-registry-data: {}

services:
  registry:
    build:
      context: docker/registry
    pull_policy: build
    image: sab-cdn-registry:latest
    container_name: sab-cdn-registry
    init: true
    networks:
      - localnet
    volumes:
      - sab-cdn-registry-data:/verdaccio/storage
    healthcheck:
      test:
        [
          'CMD',
          'wget --no-verbose --tries=1 --spider http://localhost:4873'
        ]
      start_period: 3s
      interval: 1s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    environment:
      - NPM_REGISTRY_URL=https://registry.npmjs.org
      # Either set an (bearer) auth token
      # - NPM_AUTH_TOKEN=auth-token
      # Or use username and password (basic) auth
      # - NPM_AUTH_USERNAME=username
      # - NPM_AUTH_PASSWORD=password

  server:
    depends_on:
      - registry
    build:
      context: .
      dockerfile: docker/cdn/Dockerfile
      args:
        - PORT=8080
    pull_policy: build
    image: sab-cdn-server:latest
    container_name: sab-cdn-server
    init: true
    networks:
      - localnet
    restart: unless-stopped
    environment:
      # Limit the allowed package scopes.
      # To allow only the @my-scope scope, set this to @my-scope.
      # To allow multiple scopes, provide space separated values: `@my-scope @my-other-scope`.
      # Omit the value to allow all scopes.
      # - SCOPES=@my-scope
      - ORIGIN=http://localhost
      # MAKE SURE TO OMIT THE TRAILING SLASH!
      - NPM_REGISTRY_URL=http://registry:4873
    ports:
      - 9000:8080
