storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: SAB CDN

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

uplinks:
  upstream:
    url: "${UPLINK_REGISTRY_URL}"

packages:
  '"**"':
    access: \$all
    publish: \$authenticated
    unpublish: \$authenticated
    proxy: upstream

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

log: { type: stdout, format: pretty, level: http }
